name: Test build event

on:
  workflow_dispatch: # manually triggered
    inputs:
      sha:
        description: 'Commit SHA'
        required: true
        default: ''

jobs:
  publish:
    name: Publish build event
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set develop branch tag
        run: |
          echo "ENV_TAG=dev" >> $GITHUB_ENV
          echo "UTILS_HANDLER_URL=${{ secrets.UTILS_HANDLER_URL_DEV }}" >> $GITHUB_ENV
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      -
        name: Publish build event
        run: |
          res=$(docker run --rm curlimages/curl curl -X POST ${{ env.UTILS_HANDLER_URL }}/github/event \
            -H "Content-Type: application/json" \
            --user ${{ secrets.AWS_ACCESS_KEY_ID }}:${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --aws-sigv4 "aws:amz:${{ secrets.AWS_DEFAULT_REGION }}:execute-api" \
            -d '
              {
                "event_type": "new_ipfs_image",
                "client_payload":
                {
                  "env_tag": "${{ env.ENV_TAG }}",
                  "sha_tag": "${{ github.event.inputs.sha }}",
                  "ecr_repo": "${{ steps.login-ecr.outputs.registry }}",
                  "attempt": "${{ github.run_attempt }}",
                  "image_name": "go-ipfs-${{ env.ENV_TAG }}"
                }
              }
            ') || exit 1
          echo $res
          if [[ $res != *"Forwarded event"* ]]; then
            exit 1
          fi
